### ISSUE TITLE
ROLE_CUSTOMER 기능 구현

### ISSUE THREAD

**Issue by sepang-pang** [sepang-pang/DashDine#27]
## Description

고객 권한으로 고객의 실질적인 서비스 이용 기능을 구현
식당 조회 기능, 장바구니 기능 구현

## Todo
- [x] 카테고리를 선택하면, 해당하는 식당 목록 조회
- [x] 식당 내의 메뉴를 조회할 수 있음
- [x] 2km 이내의 식당만 조회 가능, 조회 식당이 없을 시 메시지 반환
- [x] 장바구니를 통해 여러 상품 주문 가능
- [x] 1개 이상의 상품 등록 가능, 등록 간 여러 옵션 선택 가능
- [x] 장바구니에서 특정 상품을 취소할 수 있음
- [x] 장바구니에는 동일 가게 품목만 저장할 수 있음

## ETC
기타사항
