### ISSUE TITLE
주문 기능 리팩토링

### ISSUE THREAD

**Issue by sepang-pang** [sepang-pang/DashDine#47]
## Description
주문 기능 리팩토링

## Todo
- [x] 불필요한 로직 제거
- [x] 코드 가독성 향상
- [x] 누락된 기능 구현

## ETC
기타사항
