### ISSUE TITLE
메서드 명 재정의

### ISSUE THREAD

**Issue by sepang-pang** [sepang-pang/DashDine#51]
## Description
규칙적이지 않는 메서드 명 재정의함으로써 가독성 향상 도모

## Todo
- [x] 타 엔티티 조회 간 queryService 라는 레이어에 해당 조회 메서드 정의 후 호출
- [x] 단건 조회 : findOne ~
- [x] 다건 조회 : findAll ~
- [x] Repository 메서드 : find / 엔티티 명 / By / 파라미터 타입

## ETC
기타사항
