### ISSUE TITLE
메뉴 기능 리팩토링

### ISSUE THREAD

**Issue by sepang-pang** [sepang-pang/DashDine#53]
## Description
메뉴 관련 CRUD 기능들을 개선

## Todo
- [x] 조회 성능 향상
- [x] 코드 가독성 향상
- [x] 중복 로직 제거
- [x] 누락 기능 구현

## ETC
기타사항
