### ISSUE TITLE
식당 관련 누락 기능 추가 및 리팩토링

### ISSUE THREAD

**Issue by sepang-pang** [sepang-pang/DashDine#55]
## Description
식당 관련 누락 기능 추가 및 코드 리팩토링

## Todo
- [x] 식당 생성 간 위치 입력
- [x] 카테고리별 식당 조회 간 거리 기반 조회
- [ ] 식당 생성 간 이미지 등록
- [ ] 메뉴 생성 간 이미지 등록
- [x] 리뷰 및 답글 기능 구현
- [x] 리뷰 작성 간 고객이 주문한 메뉴에 대해 작성 가능
- [x] 코드 가독성 향상

## ETC
기타사항
