### ISSUE TITLE
메인 페이지 / 로그인 및 회원가입 페이지 생성

### ISSUE THREAD

**Issue by sepang-pang** [sepang-pang/DashDine#61]
## Description
메인 페이지 / 로그인 및 회원가입 페이지 생성

## Todo
- [ ] 로그인 후 고객과 사장 역할에 따라 다른 페이지로 이동
- [x] 회원가입 후 메인 페이지로 이동
- [x] 로그아웃 시 메인 페이지로 이동

## ETC
기타사항
