### ISSUE TITLE
고객 페이지 상세 구현

### ISSUE THREAD

**Issue by sepang-pang** [sepang-pang/DashDine#72]
## Description
CUSTOMER 전용 페이지를 구현하여 고객에게 다양한 기능을 제공합니다.

## Todo
- [x] 카테고리 별 식당 조회 페이지 구현
- [ ] 메뉴를 상세조회하고 장바구니에 담는 동작 구현
- [ ] 식당 리뷰 조회 동작 구현
- [ ] 장바구니에서 메뉴 및 옵션 수정 가능
- [ ] 주문내역을 조회하고, 해당 주문 상세 조회 시 수정 가능
- [ ] 본인이 작성한 리뷰를 조회할 수 있으며 수정 가능
- [ ] 마이페이지에서 닉네임, 주소, 비밀번호 등을 변경할 수 있음

## ETC
기타사항
